version: "2"
services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: phpcash
    environment:
      - MYSQL_DATABASE=cashmachine
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=123456
      - MYSQL_HOST=db
      - XDEBUG_CONFIG=remote_host=host.docker.internal
      - PHP_IDE_CONFIG=serverName=docker
    volumes:
      - .:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db
    networks:
      - default

  nginx:
    image: nginx:latest
    container_name: nginxcash
    ports:
      - 8080:80
      - 8081:81
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - php
    networks:
      - default

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmincash
    links:
      - db
    ports:
      - "8082:80"
    environment:
      - PMA_USER=root
      - PMA_PASSWORD=123456
      - PHP_UPLOAD_MAX_FILESIZE=100MB
    networks:
      - default

  db:
    image: mysql:8
    container_name: dbcash
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "6603:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=cashmachine
    volumes:
      - "mysql_data:/var/lib/mysql"
    networks:
      - default

volumes:
  mysql_data: { driver: local }

networks:
  default:
    driver: bridge
